//
// bitmapnumber.h
//

#if !defined __TINYAN_NNNEDIT_BITMAPNUMBER__
#define __TINYAN_NNNEDIT_BITMAPNUMBER__


#define BITMAPNUMBER_NEW 10
#define BITMAPNUMBER_OPEN 11
#define BITMAPNUMBER_SAVE 12
#define BITMAPNUMBER_CUT 13
#define BITMAPNUMBER_COPY 14
#define BITMAPNUMBER_PASTE 15
#define BITMAPNUMBER_DELETE 16
#define BITMAPNUMBER_UNDO 17
#define BITMAPNUMBER_DO 18
#define BITMAPNUMBER_CHANGE 19
#define BITMAPNUMBER_EDIT 20
#define BITMAPNUMBER_BACK 21
#define BITMAPNUMBER_JUMP 22
#define BITMAPNUMBER_FOWARD 23
#define BITMAPNUMBER_OVERRAP 24
#define BITMAPNUMBER_OVERRAPTYPE 25
#define BITMAPNUMBER_NOCLEAREFFECT 26
#define BITMAPNUMBER_WINDOWONOFF 27
#define BITMAPNUMBER_SEARCH 28
#define BITMAPNUMBER_SETCG 29
#define BITMAPNUMBER_BGM 30
#define BITMAPNUMBER_FRAMESPEED 31
#define BITMAPNUMBER_COMMENT_TOP 32
#define BITMAPNUMBER_COMMENT_BOTTOM 33




#endif
/*_*/

