//
// commanddatatype.h
//

#if !defined __TINYAN_NNNEDIT_COMMANDDATATYPE__
#define __TINYAN_NNNEDIT_COMMANDDATATYPE__


#define COMMANDDATATYPE_NOP 0

#define COMMANDDATATYPE_IF 1
#define COMMANDDATATYPE_ELSIF 2
#define COMMANDDATATYPE_ELSE 3

#define COMMANDDATATYPE_SELECT 4

#define COMMANDDATATYPE_STORY 5
#define COMMANDDATATYPE_FILM 6

#define COMMANDDATATYPE_BGM 7
#define COMMANDDATATYPE_BGM_CD 8
//(on off)

#define COMMANDDATATYPE_SYSTEM 9

#define COMMANDDATATYPE_CALCU 10

#define COMMANDDATATYPE_RET 11
#define COMMANDDATATYPE_NEXT 12
#define COMMANDDATATYPE_END 13

#define COMMANDDATATYPE_SCRIPT 14

#define COMMANDDATATYPE_EXIT 15

#define COMMANDDATATYPE_ENDFILM 16

#define COMMANDDATATYPE_WHILE 17

#define COMMANDDATATYPE_ENDKOMA 18

#define COMMANDDATATYPE_ENDIF 19

#define COMMANDDATATYPE_DEBUG 20

#define COMMANDDATATYPE_JUMP 21
#define COMMANDDATATYPE_SUBSCRIPT 22

#define COMMANDDATATYPE_GOTO 32

#endif
/*_*/

