//
// myResourceID.h
//

#if !defined __NNNEDIT_MYRESOURCEID__
#define __NNNEDIT_MYRESOURCEID__

//#include "winodwList.h"


//#define WINDOWBUTTON_BASE (WM_USER+100)


/*
#define ID_BUTTON_MAINSCREEN	(WINDOWBUTTON_BASE+MAINSCREEN_WINDOW)
#define ID_BUTTON_CONTE			(WINDOWBUTTON_BASE+CONTE_WINDOW)
#define ID_BUTTON_FILM			(WINDOWBUTTON_BASE+FILM_WINDOW)
#define ID_BUTTON_LAYER			(WINDOWBUTTON_BASE+LAYER_WINDOW)
#define ID_BUTTON_ZAHYO			(WINDOWBUTTON_BASE+ZAHYO_WINDOW)
#define ID_BUTTON_GAMEMESSAGE	(WINDOWBUTTON_BASE+GAMEMESSAGE_WINDOW)
#define ID_BUTTON_CONTEMESSAGE	(WINDOWBUTTON_BASE+CONTEMESSAGE_WINDOW)
#define ID_BUTTON_EFFECT		(WINDOWBUTTON_BASE+EFFECT_WINDOW)
#define ID_BUTTON_STORY			(WINDOWBUTTON_BASE+STORY_WINDOW)
#define ID_BUTTON_CONTROL		(WINDOWBUTTON_BASE+CONTROL_WINDOW)
#define ID_BUTTON_FILMCASE		(WINDOWBUTTON_BASE+FILMCASE_WINDOW)
#define ID_BUTTON_VAR			(WINDOWBUTTON_BASE+VAR_WINDOW)
#define ID_BUTTON_PROGRAM		(WINDOWBUTTON_BASE+PROGRAM_WINDOW)
#define ID_BUTTON_STORYBOOK		(WINDOWBUTTON_BASE+STORYBOOK_WINDOW)
*/




#endif
/*_*/
